### ISSUE TITLE
"Failed to load data for block entity rsgauges:contactswitch_entity" after restart

### ISSUE THREAD

**Issue by DerSoftwerker** [SmashingMods/Volcano-Block#117]
Greetings,

I have set up a server for my community and I am currently using the FTB automatic restart feature. However, after each restart the server get stuck with the following part constantly repeating int he logs:

```
[17:00:35] [Server thread/ERROR] [net.minecraft.tileentity.TileEntity]: Failed to load data for block entity rsgauges:contactswitch_entity
java.lang.StackOverflowError: null
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_221]
	at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:500) ~[?:1.8.0_221]
	at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:124) ~[avj.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:495) ~[aye.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:101) ~[ChunkIOProvider.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) ~[ChunkIOExecutor.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89) ~[on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:305) ~[amu.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:911) ~[amu.class:?]
	at wile.rsgauges.blocks.BlockSwitch$TileEntitySwitch.reset(BlockSwitch.java:758) ~[BlockSwitch$TileEntitySwitch.class:?]
	at wile.rsgauges.blocks.BlockSwitch$TileEntitySwitch.func_190201_b(BlockSwitch.java:686) ~[BlockSwitch$TileEntitySwitch.class:?]
```

I then have to restart the server manually to fix it. Not entirely sure what is the root cause for that. Any help is appreciated.
Regards,
Softwerker1

**Comment by DerSoftwerker** [comment]
I have switched to restarts via my Game hoster and the Problem still appears, although less often.
